analyzer:
  exclude:
    - 'Backend/**'
    - 'WebApp/**'
    - 'DesktopApp/**'
    - 'RandevuBurada/**'
    - 'apps/**'
    - 'data/**'
    - 'docs/**'
    - 'meta/**'
    - 'system/**'
    - 'vendor/**'
    - 'storage/**'
