<?php
/**
 * BooKi - translation dictionary sync tool
 * ----------------------------------------------------------------------------
 * Keeps every application/language/<lang>/translations_lang.php dictionary in
 * sync with the translation source files in scripts/translations/<lang>.php.
 *
 * Why this exists:
 *   The English master dictionary is the single source of truth. Every other
 *   language must expose at least the same key set, otherwise `lang('key')`
 *   falls through and renders the raw key token in the UI ("untranslated
 *   endpoint"). App_Lang adds an English fallback layer at runtime, and this
 *   tool removes the gap at build time by writing real translations.
 *
 * Usage:
 *   php scripts/sync_translations.php                 # sync every language
 *   php scripts/sync_translations.php --lang=german   # sync one language
 *   php scripts/sync_translations.php --check         # report only, exit 1 on gaps
 *   php scripts/sync_translations.php --strict        # --check + fail on any gap
 *   php scripts/sync_translations.php --scaffold=xx   # print a TSV skeleton
 *
 * The generated block is delimited by markers and is fully idempotent: running
 * the tool twice produces the same file content.
 */

if (PHP_SAPI !== 'cli') {
    exit('This script can only be run from the command line.');
}

$root = dirname(__DIR__);
$langDir = $root . '/application/language';
$sourceDir = __DIR__ . '/translations';

$markerStart = '// @translation-sync:start';
$markerEnd = '// @translation-sync:end';

// Every dictionary file starts with a CI3 direct-access guard, so BASEPATH has
// to exist before we `include` them.
if (!defined('BASEPATH')) {
    define('BASEPATH', $root . '/system/');
}

$options = [];
foreach (array_slice($argv, 1) as $arg) {
    if (preg_match('/^--([a-z-]+)(?:=(.*))?$/', $arg, $m)) {
        $options[$m[1]] = $m[2] ?? true;
    }
}

$checkOnly = isset($options['check']) || isset($options['strict']);
$strict = isset($options['strict']);
$onlyLang = is_string($options['lang'] ?? null) ? $options['lang'] : null;

/**
 * Load a dictionary file and return its $lang array.
 */
function load_dictionary(string $path): array
{
    if (!is_file($path)) {
        return [];
    }

    $lang = [];
    include $path; // phpcs:ignore
    return is_array($lang) ? $lang : [];
}

$master = load_dictionary($langDir . '/english/translations_lang.php');
if (empty($master)) {
    fwrite(STDERR, "FATAL: english master dictionary is empty or missing.\n");
    exit(2);
}

$languages = array_values(array_filter(scandir($langDir), static function ($entry) use ($langDir) {
    return $entry !== '.' && $entry !== '..' && is_dir($langDir . '/' . $entry);
}));
sort($languages);

$exitCode = 0;
$report = [];

foreach ($languages as $language) {
    if ($onlyLang !== null && $language !== $onlyLang) {
        continue;
    }

    if ($language === 'english') {
        continue;
    }

    $targetFile = $langDir . '/' . $language . '/translations_lang.php';
    $dictionary = load_dictionary($targetFile);
    $missing = array_values(array_diff(array_keys($master), array_keys($dictionary)));
    $extra = array_values(array_diff(array_keys($dictionary), array_keys($master)));

    // Scaffolding helper: dump the missing key set as "key<TAB>english value".
    if (is_string($options['scaffold'] ?? null) && $options['scaffold'] === $language) {
        foreach ($missing as $key) {
            echo $key . "\t" . str_replace(["\n", "\t"], ' ', (string) $master[$key]) . "\n";
        }
        continue;
    }

    $sourceFile = $sourceDir . '/' . $language . '.php';
    $translations = is_file($sourceFile) ? (array) require $sourceFile : [];
    // Only keys that exist in the master set are safe to inject.
    $translations = array_intersect_key($translations, $master);

    // Repair blank labels. An empty dictionary value renders as nothing, which
    // is just as broken as a raw key token, so fall back to the English master
    // value for those keys (a real translation in the source file wins).
    $blankRepairs = 0;

    foreach ($dictionary as $key => $value) {
        if ($value === '' && isset($master[$key]) && !isset($translations[$key])) {
            $translations[$key] = $master[$key];
            $blankRepairs++;
        }
    }

    if (!$checkOnly && $translations !== []) {
        $provenance = is_file($sourceFile)
            ? 'scripts/translations/' . basename($sourceFile) . '. Edit that source file and re-run the tool'
            : 'the English master (blank-label repair). Add scripts/translations/' . basename($sourceFile)
                . ' to translate these keys properly, then re-run the tool';

        $lines = [$markerStart];
        $lines[] = '// Generated by scripts/sync_translations.php from ' . $provenance;
        $lines[] = '// instead of changing this block by hand.';
        foreach ($translations as $key => $value) {
            $lines[] = "\$lang['" . $key . "'] = '" . str_replace(['\\', "'"], ['\\\\', "\\'"], (string) $value) . "';";
        }
        $lines[] = $markerEnd;
        $block = implode(PHP_EOL, $lines);

        $contents = is_file($targetFile) ? (string) file_get_contents($targetFile) : "<?php\n\n";
        $contents = rtrim($contents) . "\n";

        $startPos = strpos($contents, $markerStart);
        if ($startPos !== false && ($endPos = strpos($contents, $markerEnd, $startPos)) !== false) {
            $endPos += strlen($markerEnd);
            $contents = rtrim(substr($contents, 0, $startPos)) . "\n" . $block . rtrim(substr($contents, $endPos));
        } else {
            $contents = rtrim($contents) . "\n" . $block . "\n";
        }

        file_put_contents($targetFile, rtrim($contents) . "\n");
        $dictionary = load_dictionary($targetFile);
        $missing = array_values(array_diff(array_keys($master), array_keys($dictionary)));
        $extra = array_values(array_diff(array_keys($dictionary), array_keys($master)));
    }

    $report[$language] = [
        'total' => count($master),
        'translated' => count($dictionary) - count($missing),
        'missing' => $missing,
        'extra' => $extra,
        'repairs' => $blankRepairs,
    ];
}

if (is_string($options['scaffold'] ?? null)) {
    exit(0);
}

if (isset($options['verbose']) || $checkOnly) {
    printf("%-20s %7s %7s %7s %7s\n", 'LANGUAGE', 'TOTAL', 'HAVE', 'GAP', 'FIXED');
    foreach ($report as $language => $row) {
        printf(
            "%-20s %7d %7d %7d %7d%s\n",
            $language,
            $row['total'],
            $row['translated'],
            count($row['missing']),
            $row['repairs'],
            count($row['missing']) === 0 ? '  OK' : ''
        );
    }
}

$gapLanguages = array_filter($report, static fn ($row) => $row['missing'] !== []);
$unmatched = array_filter($report, static fn ($row) => $row['extra'] !== []);

if ($unmatched !== []) {
    fwrite(STDERR, "\nNOTE: keys not present in the English master: " . implode(', ', array_keys($unmatched)) . "\n");
}

if ($strict && $gapLanguages !== []) {
    fwrite(STDERR, sprintf(
        "\nFAIL: %d language(s) still have dictionary gaps: %s\n",
        count($gapLanguages),
        implode(', ', array_keys($gapLanguages))
    ));
    $exitCode = 1;
}

if (!$checkOnly) {
    $totalRepairs = array_sum(array_column($report, 'repairs'));

    printf(
        "\n%d/%d dictionaries natively complete. %d blank label(s) repaired." .
        " %d language(s) still rely on the runtime English fallback.\n",
        count($report) - count($gapLanguages),
        count($report),
        $totalRepairs,
        count($gapLanguages)
    );
}

exit($exitCode);

